/*
Copyright (c) 2018 Intrepid Control Systems, Inc.
All rights reserved.
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this
   list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice,
   this list of conditions and the following disclaimer in the documentation
   and/or other materials provided with the distribution.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

#ifndef _NRF51822_S130_MEMMAP_H
#define _NRF51822_S130_MEMMAP_H

#include "nrf_mbr.h"
#include "nrf_sdm.h"

// NRF51822 MBR Section 4KB
#define MBR_START (0)
#define MBR_END (0x1000)
#define MBR_MAX_SIZE (MBR_END - MBR_START)

// NRF51822 Bootloader Settings 4KB
#define BOOTLOADER_SETTINGS_START	(0x3F000)
#define BOOTLOADER_SETTINGS_END		(0x40000)
#define BOOTLOADER_SETTINGS_MAX_SIZE	(BOOTLOADER_SETTINGS_END - BOOTLOADER_SETTINGS_START)

// NRF51822 Bootloader MBR Parameter Storage 4KB
#define BOOTLOADER_MBRPARAM_START	(0x3E000)
#define BOOTLOADER_MBRPARAM_END		(0x3F000)
#define BOOTLOADER_MBRPARAM_MAX_SIZE	(BOOTLOADER_MBRPARAM_END - BOOTLOADER_MBRPARAM_START)

// NRF51822 Bootloader Region including MBR Param 28KB
#define BOOTLOADER_REGION_START		(0x38000)
#define BOOTLOADER_REGION_END		(0x3F000)
#define BOOTLOADER_MAX_SIZE			(BOOTLOADER_REGION_END - BOOTLOADER_REGION_START)

// NRF51822 Application Area 116KB
#define APPLICATION_ADDRESS_START   (0x1B000)
#define APPLICATION_ADDRESS_END		(0x38000)
#define APPLICATION_MAX_SIZE		(APPLICATION_ADDRESS_END - APPLICATION_ADDRESS_START)

// NRF51822 Softdevice Area 108KB includes 4KB MBR
#define SD_ADDRESS_START			(0x1000)
#define SD_ADDRESS_END				(0x1B000)
#define SD_MAX_SIZE					(SD_ADDRESS_END - SD_ADDRESS_START)

// NRF51822 FLASH 256KB / 4KB Pages / 512B Blocks
#define NRF51822_FLASHSIZE			(256 * 1024)
#define NRF51822_PAGESIZE			(4096)
#define NRF51822_BLOCKSIZE			(512)
#define FIRMWARE_LAST_BLOCK_INDEX	(446 * 512) // 4096 byte sectors, 447 is bootloader

#endif // _NRF51822_S130_MEMMAP_H
